### ISSUE TITLE
Special Event Dungeon [Boss] [Scaling] 

### ISSUE THREAD

**Issue by Malvarmo** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#289]
**Describe the bug**
boss in special event dungeon should scaling from 23 to 112 lvl 

**Expected behavior**
Scaling :D 

**Additional context**
https://wow.gamepedia.com/Headless_Horseman#:~:text=%22Prepare%20yourselves%2C%20the%20bells%20have,%2C%20the%20reckoning%20has%20come!%22 

Please  don't use freakz database :D

**Comment by Serithul** [comment]
Fix implemented. Will be live on the next restart. Please test it out and let us know of any issue in a new report.
