### ISSUE TITLE
[Quest]Family Heirlooms quest missing

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#324]
Quest is missing from Bold Karasshi at Pearlfin Village.

![image](https://user-images.githubusercontent.com/71927836/97392707-67229e00-191d-11eb-9412-baf36c9ce84e.png)

https://www.wowhead.com/quest=29762/family-heirlooms

**Comment by Duff-SPP** [comment]
Fixed
