### ISSUE TITLE
[Quest]SI:7 Report: Take No Prisoners quest giver is missing

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#329]
Quest Giver Amber Kearnen is missing in at Pearlfin Village

![image](https://user-images.githubusercontent.com/71927836/97396510-342ed900-1922-11eb-98c2-a871931ccd78.png)

https://www.wowhead.com/quest=29727/si-7-report-take-no-prisoners

**Comment by Duff-SPP** [comment]
Fixed
