### ISSUE TITLE
[Quest]Seek Out the Lorewalker quest giver is missing

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#332]
Quest giver Bold Karasshi is missing at Pearlfin Village

![image](https://user-images.githubusercontent.com/71927836/97397780-04350500-1925-11eb-8a56-4acd7613715c.png)

I cant turn in quest to the Mouthwatering Brew too.

![image](https://user-images.githubusercontent.com/71927836/97399255-b968bc80-1927-11eb-91f1-b51233bce1e5.png)

https://www.wowhead.com/quest=29888/seek-out-the-lorewalker

**Comment by Duff-SPP** [comment]
Fixed the quest turn in issue 2 

the quest giver wont show because you need to progress in the questline / for issue number 1 mentioned in this post
