### ISSUE TITLE
[Quest]Borrowed Brew quest is missing

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#333]
Can't take the quest, maybe due to the quest before being uncompletable.

https://www.wowhead.com/quest=29888/seek-out-the-lorewalker

https://www.wowhead.com/quest=29889/borrowed-brew

**Comment by Duff-SPP** [comment]
Borrowed brew is apart of quest line, you need to complete all quests in order to get borrowed brew
