### ISSUE TITLE
[Quest]An Ancient Legend quest giver is missing

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#336]
Quest Giver Lina Whitepaw is missing at Den of Sorrow.

![image](https://user-images.githubusercontent.com/71927836/97401059-19ad2d80-192b-11eb-8a54-21609bffb93d.png)

Interacting with the quest objective, Scroll of Sorrow, does not give you song of the vale.

https://www.wowhead.com/quest=29900/an-ancient-legend

**Comment by Duff-SPP** [comment]
Fixed
