### ISSUE TITLE
[Quest]Anduin's Decision quest giver is missing

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#337]
Quest giver and quest objective, Anduin Wrynn is missing at Den of Sorrow.

![image](https://user-images.githubusercontent.com/71927836/97401353-a0620a80-192b-11eb-88b4-3bc5045db64e.png)

https://www.wowhead.com/quest=29901/anduins-decision

**Comment by Duff-SPP** [comment]
Fixed
