### ISSUE TITLE
[Quest]Let them Burn quest is missing

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#338]
Quest giver Admiral Taylor doesn't give out the quest Carp Diem at Pearlfin Village.
He seems to not be in the original position where you can get the quest too.

![image](https://user-images.githubusercontent.com/71927836/97401687-3a29b780-192c-11eb-9e82-3211419a6040.png)

https://www.wowhead.com/quest=29905/let-them-burn

**Comment by Duff-SPP** [comment]
Fixed
