### ISSUE TITLE
[Quest]Carp Diem quest is missing

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#339]
Quest giver Admiral Taylor doesn't give out the quest Carp Diem at Pearlfin Village.
He seems to not be in the original position where you can get the quest too.

![image](https://user-images.githubusercontent.com/71927836/97401682-37c75d80-192c-11eb-94d6-999e21b3a40b.png)

https://www.wowhead.com/quest=29906/carp-diem

**Comment by Duff-SPP** [comment]
Fixed
