### ISSUE TITLE
[Bug] Fangs of Devourer Model

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#340]
**Describe the bug**
The model of the fangs of the devourer is changed with a different model

**Expected behavior**
The model should show the fangs of the devourer.

**Screenshots**
![image](https://user-images.githubusercontent.com/71482732/97401877-9df5b580-1917-11eb-8078-4ca5dbf286dc.png)

**Comment by Duff-SPP** [comment]
Fixed
