### ISSUE TITLE
[Quest]All we can Spare quest Free Ride missing

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#348]
In the quest All we can Spare, you would be able to get a free ride to emperor's omen by speaking to Toya, however i was not able get it.

![image](https://user-images.githubusercontent.com/71927836/97549151-02457180-1a0b-11eb-85f8-635691e10fdc.png)

https://www.wowhead.com/quest=29925/all-we-can-spare

**Comment by Duff-SPP** [comment]
Fixed
