### ISSUE TITLE
[Quest]Mann's man quest npc is misplaced

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#349]
Quest NPC Hao Mann is 1 floor below the original position.
Original:
![image](https://user-images.githubusercontent.com/71927836/97549679-a0393c00-1a0b-11eb-8a6b-ee24f7d4a2c0.png)
Where he is rn:
![image](https://user-images.githubusercontent.com/71927836/97549729-b810c000-1a0b-11eb-9791-d4b663aa5107.png)
https://www.wowhead.com/quest=29927/manns-man

**Comment by Duff-SPP** [comment]
Fixed
