### ISSUE TITLE
[Quest]An Unexpected Advatage quest giver missing

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#359]
Quest giver Sully "The Pickle" McLeary is missing at Pearlfin Village.

![image](https://user-images.githubusercontent.com/71927836/97672169-87409180-1ac4-11eb-81e2-bc72291d03c8.png)

https://www.wowhead.com/quest=30565/an-unexpected-advantage

**Comment by Duff-SPP** [comment]
Fixed
