### ISSUE TITLE
[Skill] "Death from Above"

### ISSUE THREAD

**Issue by AlveronAlsv** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#368]
Rogue skill "Death from Above" sends a character into space when used.
![image](https://user-images.githubusercontent.com/71718884/97721563-a518f100-1ada-11eb-979d-9a890b87e328.png)

**Comment by AlveronAlsv** [comment]
https://www.wowhead.com/spell=152150/death-from-above

**Comment by acidmanifesto** [comment]
this was fix in full a month ago. please close.
