### ISSUE TITLE
[Quest]Lin Tenderpaw quest giver missing

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#428]
Quest giver Xiao is missing at Pang's Stead. Turn-in NPC Lin Tenderpaw is missing at Stoneplow.
![image](https://user-images.githubusercontent.com/71927836/98221981-3da3eb00-1f8b-11eb-8ba5-37fb14ecda12.png)
https://www.wowhead.com/quest=29872/lin-tenderpaw

**Comment by takasi689** [comment]
NPC: [Lin Tenderpaw](https://www.wowhead.com/npc=56111/lin-tenderpaw) was placed and will be available after next server restart.
Thank you for report.
Best Regards
