### ISSUE TITLE
[Spell] Warrior's Charge

### ISSUE THREAD

**Issue by Norflok** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#450]
**Describe the bug**
Some bugs in the charge ability for warrior:
- Charge only generates 18 or 19 rage instead of 20 (probably because of rage drain tick outside of combat)
- No shoulder bash animation
- No auto attack immediately after using charge

**To Reproduce**
1. Use "Charge" ability on warrior

**Expected behavior**
- Charge should always generate 20 rage
- Character should auto attack immediately after using charge
- Shoulder bash animation should happen on hit

**Comment by acidmanifesto** [comment]
https://youtu.be/7T0wSkIXTZI
Patch sent in.
