### ISSUE TITLE
[Hunter] [Spell] "Dire Beast" summons a random beast that is supposed to attack enemy for 8 seconds

### ISSUE THREAD

**Issue by ralphhorizon** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#467]
When i summon a dire beast, a random beast is summoned that does NOT attack the enemy, and when you "interact" with it, it opens a flight path window.

Cast "Dire Beast"
"interact/talk with it"

Supposed to summon a random beast to attack enemy target for 8 seconds, 2 charges on the spell.

**Comment by acidmanifesto** [comment]
This i am unable to replicate. Is this still a issue?
