### ISSUE TITLE
[NPC] Iris Moondreamer missing

### ISSUE THREAD

**Issue by MayuzumiSayaka** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#470]
**Describe the bug**
She doesn't exist

**To Reproduce**
Go to her cords, https://www.wowhead.com/npc=71304/iris-moondreamer#sells (62.8 , 24.2)

**Expected behavior**
She's supposed to be here

**Screenshots**
https://i.imgur.com/jGfWsyv.png

**Comment by Serithul** [comment]
Fixed
