### ISSUE TITLE
[Text][Quest]Wrong Language for Sealing Fate: Marks of Honor

### ISSUE THREAD

**Issue by KCorruption** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#474]
**Describe the bug**
Quest "Sealing Fate: Marks of Honor" text is shown entirely in Russian/Cyrillic instead of English.

**To Reproduce**
1. Go to Broken Shore Dalaran & Find Archmage Lan'dalok near the Violet Hold.
2. Interact with NPC and select the quest "Sealing Fate: Marks of Honor"
3. See bug.

**Expected behavior**
Language for quest text should be English.

**Screenshots**
https://cdn.discordapp.com/attachments/748625847421763721/777003032818745374/unknown.png

**Additional context**
https://www.wowhead.com/quest=47851/sealing-fate-marks-of-honor

**Comment by acidmanifesto** [comment]
patch is sent in. will be live in the next restart
