### ISSUE TITLE
[Hunter] Pet

### ISSUE THREAD

**Issue by talosbane00** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#489]
I am not an expert for this class (damage / skill numbers), this is a list of every issues that I have found:

1) Pet is slow to follow the player or it stops moving suddenly.
2) Many pathfinding issues: Pet often "floats", if there are more levels it "gets stuck" and stops following the player (and you are forced to spamclick on "follow player" ability to unstuck)
3) Sometimes it can buggy the target that evades every attacks and you are forced to dismiss pet
4) When Pet is summoned his abilities / settings reset and you must change it everytime
5) Pet often does not attack the target that player is attacking and player is forced to use the pet's ability to force the attack (wasting time)

-UPDATE-
6) Personal pet or Hati or both of them have pathfinding issues as you can see here:
![Pet3](https://user-images.githubusercontent.com/60328315/99260391-97be6f00-281b-11eb-8bbf-441b699fb70d.jpg)

7) Hati often do no attack target and you must use spell or force attack as you can see in first screenshot and second screenshot.
![Pet1](https://user-images.githubusercontent.com/60328315/99260489-bb81b500-281b-11eb-997d-e19b1fe11d78.jpg)

8) Seems that Blink Strike [https://www.wowhead.com/spell=130393/blink-strike](url) (but I'm not sure about it) can bug a target that you are attacking because pets and target "blink" in air as you can see in this screenshot:
![Pet1](https://user-images.githubusercontent.com/60328315/99260871-406cce80-281c-11eb-95c5-c494c60f4879.jpg)
I hope that this can not happen also with Elite or Boss.

9) If you choose "Assist" your pet should start to attack your target ONLY if you start attacking but many times seems that that stance is like "Defensive" because Pet many times starts to attack a target if that target starts to attack him and that's should not be happen.

10) You are also forced to loot from a corpse if it is in air. Unfortunally if that corpse is too far away from you is not possible to loot:
![Pet2](https://user-images.githubusercontent.com/60328315/99261098-8b86e180-281c-11eb-8421-981917fafb2b.jpg)

Sorry for my english

**Comment by markovejnovic** [comment]
Experienced slowness on mage elemental too.
Same issue with abilities moving on the cast bar when dismissing pet and summoning it again.

**Comment by markovejnovic** [comment]
Also, water elemental moves to melee range in-between casts, inching closer to the target every time.

**Comment by markovejnovic** [comment]
> When Pet is summoned his abilities / settings reset and you must change it everytime

This now works as expected on frost ele. Abilities are saved.
