### ISSUE TITLE
[Monk] Stagger

### ISSUE THREAD

**Issue by jacobx97** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#496]
**Describe the bug**
Stagger seems to not be implemented.

**To Reproduce**
1. Get damage as brewmaster monk with Stagger passive

**Expected behavior**
When you take damage, 40% (75% with Iron Skin Brew) of the damage shoud be applied as 10 second DoT.

**Screenshots**
![Snímka obrazovky 2020-11-14 141345](https://user-images.githubusercontent.com/74407627/99147742-aa9e3b80-2683-11eb-9028-ec8d73212157.png)

**Additional context**
https://www.wowhead.com/spell=124255/stagger#changelog

**Comment by jacobx97** [comment]
I have just made level 20 and get Ironskin Brew. After using this ability Stager started damaging me.

**Comment by acidmanifesto** [comment]
![image](https://user-images.githubusercontent.com/16887899/122627883-760eba00-d080-11eb-88d3-fd54f8ac767c.png)
Ok let me explain how stagger works here so far. as this is a extremely difficult spell to script. Currently we have a 3 bar on the bottom next to the player portrait. Thats the sum of all your health. It is set up Damage/Health.
So what stagger does is delay the total amount of damage your recieved in accordance with your overall health and will then slowly and in small incremements apply it to you character as damage. once the total amount of damage is ticked down to zero you will stop recieving damage.
