### ISSUE TITLE
[Demon Hunter Havoc] Eye Beam

### ISSUE THREAD

**Issue by toamuka** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#518]
https://www.wowhead.com/spell=198013/eye-beam

Eye Beam is cancelled upon moving. 

Eye Beam should only be cancelled if the player is stunned, silenced, interrupted or casts another ability during Eye beam's duration.

There is a -200% speed aura applied to the demon hunter which is for the case of allowing the Demon Hunter to use this ability shortly after using Vengeful Retreat or even during the movement of this ability.

https://youtu.be/dGiwMEoB7aM?t=177

In this video at the timestamp. I am using Eyebeam during Vengeful Retreat to hit all the oozes, notice how Eyebeam is at 50% of it's duration whilst im still in mid air, channeling this ability WHILST MOVING.

**Comment by acidmanifesto** [comment]
This was fixed 2 months ago i believe. late in november or decement. please close
