### ISSUE TITLE
[Demon Hunter Artifact Trait Skill] Inner Demons

### ISSUE THREAD

**Issue by toamuka** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#519]
https://www.wowhead.com/spell=201471/inner-demons

Sometimes this ability misses completely and the visual and effect of the Inner Demon lands a good 20 yards away from where you are fighting and deals no damage or hits mobs that you aren't fighting.

This is reproducible at areas like Temple of Elune (Vaslharah) and a lot of places where hills and ramps are.

How it should work: when it procs from Chaos Strike it should land directly ontop of the target and deal damage in an AoE.

**Comment by markovejnovic** [comment]
Wrong link, right link [here](https://www.wowhead.com/spell=201471/inner-demons)

**Comment by toamuka** [comment]
> Wrong link, right link [here](https://www.wowhead.com/spell=201471/inner-demons)

thanks 👍

**Comment by acidmanifesto** [comment]
This issue was fixed a while back. I will be closing the ticket now. Let me know if there is any further issues with it
