### ISSUE TITLE
[Demon Hunter Talent] Demonic

### ISSUE THREAD

**Issue by toamuka** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#521]
https://www.wowhead.com/spell=213410/demonic

How it is:
Demonic has no cap on how many times you can add the 8 seconds to your metamorphosis.

How it should be:

**Whilst in Metamorphosis** (30) you can Eye Beam ONCE for a total of 38 seconds, any other Eye-Beams will not add to the duration.

**Whilst out of the Metamorphosis** you can Eye Beam to activate metamorphosis for 8 seconds, any other Eye-beams during this will not add to the duration.

fat proofs:

https://www.youtube.com/watch?v=_OkkD5Zh3Wo
https://www.mmo-champion.com/threads/2389443-Demonic-Double-Eye-Beam-during-Meta
https://www.mmo-champion.com/threads/2343038-Demonic-Eye-Beam-while-in-Demon-Form-duration

In youtube video you can see it gets to 5 seconds and only refreshes when the buff is gone.

**Comment by acidmanifesto** [comment]
This issue was fixed a while back. I will be closing the ticket now. Let me know if there is any further issues with it
