### ISSUE TITLE
[Mage] Blink is unusable.

### ISSUE THREAD

**Issue by markovejnovic** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#523]
**Describe the bug**
More often than not, blink will either:
* Blink you vertically, as high as a jump
* Blink you under the terrain

**Expected behavior**
Blink should blink you a horizontal distance `d` in the direction you are facing, to the `z` height, where `z = lerp(nearest terrain vertices at d) + small constant`

**Comment by acidmanifesto** [comment]
this was fixed with last major update a month ago. please close.
