### ISSUE TITLE
[NPC]Aronus is together with his enemy twin

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#524]
Aronus is phased together with the Horde Aronus making it hard to ride him for the quest "As Hyjal Burns".
![image](https://user-images.githubusercontent.com/71927836/99150261-2f15ac00-26ce-11eb-8b62-c1ab00cea4da.png)

**Comment by acidmanifesto** [comment]
issue fixed by @skeezerbean
