### ISSUE TITLE
[Quest]As Hyjal Burns is not working

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#525]
Vehicle Aronus does not move/progress after you ride on his back. You also can't get off him without relogging.
![image](https://user-images.githubusercontent.com/71927836/99150341-d397ee00-26ce-11eb-9f92-343b690ef88a.png)
https://www.wowhead.com/quest=25316/as-hyjal-burns

**Comment by acidmanifesto** [comment]
issue fixed by @skeezerbean
