### ISSUE TITLE
[Quest] Quest Scaling

### ISSUE THREAD

**Issue by Norflok** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#529]
**Describe the bug**
Quests don't scale to your level. They will go green/grey if you outlevel them even if you're within the zone level range. The quest reward will also be reduced.

**Expected behavior**
Quests and their reward should scale to your level while you're within the zone level range

**Comment by takasi689** [comment]
Could you please provide area where issues happened.

**Comment by Norflok** [comment]
All leveling areas. 

https://wow.gamepedia.com/Zones_by_level_(Cataclysm)

**Comment by Norflok** [comment]
For example, in legion 7.3 Westfall should be 10-60. 
In the current Quest Scaling, you will outlevel the area quest by the time you're lvl 15+, which shouldn't happen because you're still within the 10-60 range

**Comment by Norflok** [comment]
Forgot to add, the gear from quests scale properly. Only the xp and gold ( I'm not sure about gold reward) don't scale properly.

**Comment by Serithul** [comment]
Addressed a couple of months ago. Closing.
