### ISSUE TITLE
" We have 8 non-completable quests in whole legion". Hmm...no.

### ISSUE THREAD

**Issue by talosbane00** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#538]
I'm stuck at level 105. Scouting map works but every starting quest is not working. 

I ask to you some help with an autocomplete quest and you said that "I must search quests in other zones".

"8 non-completable quests in whole legion"? No.

Seems not a PTR but an Alpha. Better than other Alpha but just an Alpha.

I'm sorry.

**Comment by takasi689** [comment]
🤔You could've at least provide quest and area where you got stuck.

**Comment by talosbane00** [comment]
I open a ticket on Discord immediately and I ask an autocomplete for a quest for Stormheim (first chain quest)'cause usually that specific stage is ever bugged (I played in many legion pserver) and usually after that stage you can continue quest. A GM said to me:"That quest is bugged, search in other zones". Really?

And...I'm actually stucked at level 105 'cause I can't start/complete first quests in every zones ("best" zones is Highmountain).

So...don't say that "there are only 8 quests that are not completable" 'cause that is absolutley false 'cause I know that is a PTR but not in this way. In this way this is an Alpha. I was an alpha and beta tester in many legion pserver (unfortunally) with thousands tickets opened and I know what I'm talking about. 

This is not a flame. But I'm just a bit tired 'cause I'd like to play this expansion but seems that noone can make a good server.

**Comment by takasi689** [comment]
I get what you're trying to say and I apologize on behalf of the team, but again you didn't respond to my question. :/
Developers need to know what quest it doesn't work so we can fix that asap. 
Best Regards

**Comment by talosbane00** [comment]
"but again you didn't respond to my question. :/
Developers need to know what quest it doesn't work so we can fix that asap."

Are you kiddin me? 

...as I said I open a ticket on bugtracker (ID Ticket 522) and after that I also open a ticket on Discord and I ask a GM an autocomplete and He said:"I know that quest is bugged, please go to another zone".

I don't need any apologize but I also don't need any excuse.

Best Regards

**Comment by acidmanifesto** [comment]
I know i never made the claim of 8 non completable quests for legion. If someone did make that claim it wasnt me or based on info by me.  A list of what the issue is can be helpful. I never got pulled or notified of a ticket and do t have access to them.
