### ISSUE TITLE
Green area on map in Broken Shore

### ISSUE THREAD

**Issue by talosbane00** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#554]
![Immagine](https://user-images.githubusercontent.com/60328315/99191767-17dacb00-276f-11eb-94ae-4835749a2dcb.png)

**Comment by acidmanifesto** [comment]
thats from using a minimal client. either sit and wait for your client to pull the rest of the data or download the full client of 26972.

**Comment by talosbane00** [comment]
I'm actually using a full client ^^''

**Comment by Serithul** [comment]
Then your client has either corrupt or missing files. I've encountered this issue myself on many private servers. I can only suggest either extracting your client again from it's .zip file or redownloading it.

**Comment by talosbane00** [comment]
*sadface* Fortunally I have 200MBs. Thanks, I'll try to download again it.
