### ISSUE TITLE
[Quest] Classy Glass- Ogre's Monocle does not always drop 

### ISSUE THREAD

**Issue by mrlifelesss** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#564]
**Describe the bug**
When you kill [Zzarc' Vul](https://www.wowhead.com/npc=300/zzarc-vul), he does not drop the quest item: [Ogre's Monocle](https://www.wowhead.com/item=1968/ogres-monocle#comments)

**To Reproduce**
1. Take the Quest [Classy Glass](https://www.wowhead.com/quest=26685/classy-glass)
2. Kill [Zzarc' Vul](https://www.wowhead.com/npc=300/zzarc-vul) & loot his body
3. Notice he did not drop the needed quest item.

**Expected behavior**
When you kill Zzarc' Vul he should drop the quest item.

**Screenshots**
![image](https://user-images.githubusercontent.com/74491617/99246308-c3d2f380-280d-11eb-8e91-662ecc62508b.png)

**Additional context**

**Comment by acidmanifesto** [comment]
Patch is sent in. Will be live in next restart
