### ISSUE TITLE
[Artifact Quest] Havoc: The Thieving Apprentice

### ISSUE THREAD

**Issue by toamuka** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#572]
https://www.wowhead.com/quest=47043/havoc-the-thieving-apprentice
https://www.wowhead.com/npc=115791/joanna

Joanna doesn't exist outside the tower where she should be and isn't the quest hand-in NPC when she should be.

**Comment by Serithul** [comment]
Fixed. Will be live on the next restart.
