### ISSUE TITLE
[Quest]The Sixth quest giver is missing in Dalaran

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#582]
Warlock Class Order Hall starter Quest giver is missing in Dalaran. Due to this I am unable to get any of the Artifact weapons for warlocks.
![image](https://user-images.githubusercontent.com/71927836/99329893-22ee4200-28ba-11eb-85a8-331e16d31e5c.png)
https://www.wowhead.com/quest=40716/the-sixth

**Comment by sausagemadness** [comment]
Marking duplicate : https://github.com/Project-AuroraWoW/Project-Aurora/issues/107

**Comment by sausagemadness** [comment]
This was just tested out. A relog should fix the issue or the player needs to ensure they are in New Dalaran. I was able to boost a player with the legion script scroll and ended up in new dalaran. the first time a quest giver did not run up to me. After a relog the character did run up to me with a quest. Suggest closing this.
