### ISSUE TITLE
[Quest]The Codex of Ra quest objective does not get completed

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#585]
Quest Objective Travel To Guo-Lai Halls does not get completed when entering Guo-Lai Halls.
Quest Objectives seems to be missing, maybe due to the area not getting phased for the artifact questline.
![image](https://user-images.githubusercontent.com/71927836/99347109-2b05ac00-28d1-11eb-8318-3482150d33ef.png)
https://www.wowhead.com/quest=43338/the-codex-of-ra

**Comment by acidmanifesto** [comment]
Patch sent in. 
![image](https://user-images.githubusercontent.com/16887899/111553175-2f948100-875a-11eb-84a9-794b14915abc.png)
