### ISSUE TITLE
[Quest]The Voice of Thunder quest 

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#586]
Quest is Available together with The Coming Storm in The Maelstrom.
Reghar Earthfury and Xuen doesn't move after speaking with Xuen.
![image](https://user-images.githubusercontent.com/71927836/99346457-a5cdc780-28cf-11eb-8ccd-ed46dd6124b6.png)
https://www.wowhead.com/quest=39771/the-voice-of-thunder#

**Comment by sausagemadness** [comment]
Marking as duplicate : https://github.com/Project-AuroraWoW/Project-Aurora/issues/184
