### ISSUE TITLE
[Quest] Maritime Law

### ISSUE THREAD

**Issue by MayuzumiSayaka** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#588]
**Describe the bug**
Quest is not available from Mr. Shackle

**To Reproduce**
Go to Mr. Shackle in Shackle's Den and see for yourself

**Expected behavior**
Supposed to be able to get the quest from him to start the questline https://www.wowhead.com/quest=37654/maritime-law

**Comment by sausagemadness** [comment]
Have you completed the quest [The Prince is Going Down](https://www.wowhead.com/quest=37566/the-prince-is-going-down)?

**Comment by MayuzumiSayaka** [comment]
yes, apparently it was a bug with https://www.wowhead.com/quest=38857/a-favor-for-mr-shackle 
you can't get the quest from the npc

**Comment by sausagemadness** [comment]
From my review of the legion questlines, I was able to complete the quest. You should've gotten it right around then :)

**Comment by MayuzumiSayaka** [comment]
From my gameplay that I did, I was not able to even get the starting quests for part 5 of Azsuna. You should've checked right around again :)

**Comment by sausagemadness** [comment]
Please do go through this review of working legion quests. I had prepared this about 2 months ago on custom. :)
[Zone_Quests_List.xlsx](https://github.com/Project-AuroraWoW/Project-Aurora/files/5555114/Zone_Quests_List.xlsx)

**Comment by MayuzumiSayaka** [comment]
No :)

**Comment by joey2801** [comment]
I can confirm the quest line does work... the issue is when not completing https://www.wowhead.com/quest=38857/a-favor-for-mr-shackle
