### ISSUE TITLE
A choice of allies quest

### ISSUE THREAD

**Issue by bobacaric2** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#590]
**Describe the bug**
Can not make a choice as there is no option to do so. I get to see what allies i can get by talking them but can not chose one when i talk to Sylvanas.

**To Reproduce**
1. Get Call for allies quest, go to Sylvanas, Talk... Chose an ally.

**Expected behavior**
You should be able to make a choice: https://www.youtube.com/watch?v=hL6EAu1aCbY&ab_channel=Blizzplanet

**Screenshots**
http://prntscr.com/vkrcuk

**Additional context**

**Comment by acidmanifesto** [comment]
You need to meet the requirements between the two allied races for the options to show up

You need to complete specific storyline achievements to enable the questline to unlock each Allied race.

These achievement can be completed on the opposite faction as well (like completing them on an Alliance character for the Horde allied races), but you will need to have a level 110 of the corresponding faction to complete the questline to unlock them.

Nightborne: Completion of  Insurrection
Void Elf: Completion of  You Are Now Prepared!
Lightforged Draenei: Completion of  You Are Now Prepared!
Highmountain Tauren: Completion of  Ain't No Mountain High Enough
