### ISSUE TITLE
[WQ] Rage of the Owlbeasts

### ISSUE THREAD

**Issue by talosbane00** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#591]
[https://www.wowhead.com/quest=43324/rage-of-the-owlbeasts](url)

When you hit 33% nothing change if you continue to kill Owlbeasts or Undulating Boneslime or if you save Sisters of the Moon.

It's impossible to complete this World Quest.

**Comment by joey2801** [comment]
Issue fixed

**Comment by talosbane00** [comment]
I just tried and now area doesn't trigger. Fix will be ready with next restart?

**Comment by joey2801** [comment]
Correct 😄 most fixes I've done this morning will only change on server restart
