### ISSUE TITLE
[WQ] Bloodline of Stone

### ISSUE THREAD

**Issue by talosbane00** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#592]
[https://www.wowhead.com/quest=41955/bloodline-of-stone](url)
[https://www.wowhead.com/npc=96932/hatching-harpy-egg](url)

It's not possible to break any eggs . Impossible to complete this World Quest.

**Comment by joey2801** [comment]
Break eggs by walking on them, works for me

**Comment by talosbane00** [comment]
But the eggs shouldn't be broken already, that's why I thought the world quest was bugged. So it's a visual bug.  
Because I tried to walk over some eggs and nothing happened.  it didn't work with some. I'll try again.

**Comment by joey2801** [comment]
I saw some eggs broken, but the ones I walked over worked when unbroken 😃
