### ISSUE TITLE
Changing zone can stuck Pets somewhere

### ISSUE THREAD

**Issue by talosbane00** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#596]
I was in Dalaran with Hati and other pet and I dismiss my pet and I remove my Artifact Weapon (to remove Hati)
After using portal to Dalaran I could not summon both of them.
Client warns me with the message:"You must dismiss your current pet first."
Seems that my 2 pets weren't with me anymore.

For fixing this bug I am forced to log out and log in and sometimes my character take a sort of rollback and I go back to last flightpath.
![pet bug](https://user-images.githubusercontent.com/60328315/99431886-b439d480-290b-11eb-88a9-859816d6d2e6.jpg)
![pet bug2](https://user-images.githubusercontent.com/60328315/99431902-b7cd5b80-290b-11eb-8e0d-8e7fb905c39f.jpg)

**Comment by acidmanifesto** [comment]
Issue was fixed 2 days ago. Let me know if the ossue arises again.
