### ISSUE TITLE
[Quests] TBC drop rates

### ISSUE THREAD

**Issue by Deathworgen123** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#597]
Drop rates seem to be really for quest item in TBC zones.
Quests where this happened were https://www.wowhead.com/quest=10450/bonechewer-blood and https://www.wowhead.com/quest=10660/what-strange-creatures
The associated mobs also don't display their quest markers so without prior knowledge/quest text you won't be able to tell which ones you need to kill.

**Comment by joey2801** [comment]
Checked loot tables, they in-line with retail
