### ISSUE TITLE
Quest in Argus: Invasive Species can't collect 30 items you need

### ISSUE THREAD

**Issue by bobacaric2** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#598]
**Describe the bug**
You need to kill some mobs here and there and collect 30 Partially digested Arcana, it works well until you reach 29 of those. After that if you try to collect more it says: You can not carry any more of that item.  I relogged just in case, but didn't help.

**To Reproduce**
1. Go to Mac'Are, get the quest from Archmage Y'mera and accept the quest. 

**Expected behavior**
You should be able to collect 30 Partially digested Arcana and that's it. I couldn't collect all 30. 

**Screenshots**
http://prntscr.com/vl1sx0

**Additional context**

**Comment by joey2801** [comment]
I too got this error, it was due to the number being higher than what i could loot... however the quest objective was compelted anyway
upon killing 5 manafeeders i completed the objective to the quest with no issue
