### ISSUE TITLE
World quest: Wrangler Kravos the mob doesn't spawn

### ISSUE THREAD

**Issue by bobacaric2** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#599]
**Describe the bug**
He is not there, i checked the yt if i am in the right place, and walked around but he wasn't anywhere.

**To Reproduce**
1. Go to 'Mac'are - Triumvirate end - 

**Expected behavior**
He should spawn there, i waited, a bit just in case if he needed time. Questline is finished here so he should be there. 

**Screenshots**
http://prntscr.com/vl2av1

**Additional context**

**Comment by joey2801** [comment]
Creature was phased out, fixed...
