### ISSUE TITLE
[NPC] Dead on the ground

### ISSUE THREAD

**Issue by upal212** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#601]
**Describe the bug**

https://www.wowhead.com/npc=45517/ravaged-dire-wolf
All the Ravaged Dire Wolf is dead on the ground in Brightwood Grove, Darkshire as shown in the screenshot.

**To Reproduce**

Could not find a way around the bug.

**Expected behavior**
NPC should be alive and walking around - respawn after being killed/dead

**Screenshots**
https://imgur.com/a/6M7ObCY

**Additional context**
-

**Comment by joey2801** [comment]
Issue fixed

**Comment by Serithul** [comment]
Actually they shouldn't be up and walking nor be able to be killed. Check the comments on that wowhead link you shared. It's also stated on this link on the creature's tooltip on the right, Deceased. https://wow.gamepedia.com/Ravaged_Dire_Wolf
