### ISSUE TITLE
[Quest] As Hyjal Burns

### ISSUE THREAD

**Issue by GiulianoMSA** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#602]
Aronus doesn't fly, and you can only dismount him by relogging(afaik)

1. Get quest in moonglade.
2. Try to mount Aronus

**Expected behavior**
Aronus is supposed to fly you around Mount Hyjal and then drop you at Nordrassil while doing some scripted talking.

**Comment by acidmanifesto** [comment]
issue fixed by @skeezerbean
