### ISSUE TITLE
[Quest] Lightning in a Bottle (Mount Hyjal)

### ISSUE THREAD

**Issue by GiulianoMSA** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#609]
Can't interact with quest objects (lightning rods)

**To Reproduce**
1. Get quest.
2. Try to interact with lightning rods.
3. Fail

**Expected behavior**
The Twilight Lightning Channels should be interactable objects to collect a Charged Condenser Jar

**Comment by joey2801** [comment]
Tried on both alliance and horde, i get the item
