### ISSUE TITLE
[Quest] From the Mouth of Madness (Mount Hyjal)

### ISSUE THREAD

**Issue by GiulianoMSA** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#610]
Can't collect/interact with Stoneblood (Pinkish/orange stone flowers). The other 2 quest objects function properly.

1. Get quest.
2. Fail to interact with Stoneblood

**Expected behavior**
Stoneblood should be collectable.

**Comment by joey2801** [comment]
Issue Fixed
