### ISSUE TITLE
[Quest] Through the Dream (Mount Hyjal)

### ISSUE THREAD

**Issue by GiulianoMSA** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#611]
Nothing happens when you get the quest. You can't complete it because the npc doesn't follow you.

1. Get quest.
2. See that nothing happens.

**Expected behavior**
A version of Archdruid Fandral Staghelm should be created to follow you when you get the quest.

**Comment by acidmanifesto** [comment]
Fixed in last update by @skeezerbean
