### ISSUE TITLE
[Quest] The Prophet's Gambit

### ISSUE THREAD

**Issue by talosbane00** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#635]
[https://www.wowhead.com/quest=46732/the-prophets-gambit](url)

Stage "Stand with Velen" works but "Follow Velen" doesn't works.
You cannot complete this quest.

**Comment by talosbane00** [comment]
-UPDATE-
It's possible to complete that stage but you must run and stay literally "inside" Velen. But it's not so easy.
Anyway it need a little fix for triggering area.

**Comment by acidmanifesto** [comment]
This was addressed a couple of months ago. Issue is corrected.
