### ISSUE TITLE
Quest: Vault of the Wardens: Vault Break-In, The quest item doesn't drop from Last Boss.

### ISSUE THREAD

**Issue by bobacaric2** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#637]
**Describe the bug**
Sargerite keystone should be dropped by Cordana Felsong upon killing her, but it doesn't. Tried both on normal and heroic, after succsesfully clearing all bosses, the keystone didn't drop either time.

**To Reproduce**
1. Go to - demon hunter class hall - take a quest then go to Vault of the wardens dungeon in Azhara - go to the last boss and kill. 

**Expected behavior**
Upon death of Cordana she should drop the sargerite keystone.

**Screenshots**
https://www.wowhead.com/quest=42752/vault-of-the-wardens-vault-break-in
https://wow.gamepedia.com/Vault_of_the_Wardens:_Vault_Break-In
https://www.youtube.com/watch?v=edtBTIivAfU&t=180s&ab_channel=WoWJNasty

**Comment by acidmanifesto** [comment]
patch sent in. tested 4 times

**Comment by Serithul** [comment]
Fix is live. Let us know if there's a problem with it.
