### ISSUE TITLE
[Quest] Honoring Success - Rogue Class Hall

### ISSUE THREAD

**Issue by GiulianoMSA** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#638]
Vanessa VanCleaf is not scaled down to your level - she's always level 110 with full power...
That means as a level 100 who just got their artifact weapon and has barely any legion level gear, she's Skull and pretty much unkillable.

**Expected behavior**
Vanessa VanCleaf is supposed to scale to your level, as seen here:
https://www.youtube.com/watch?v=tzkNsLQDqR8

**Comment by acidmanifesto** [comment]
this was patched a few months ago. please close.
