### ISSUE TITLE
[Quest]Too Big for his Britches quest item does not drop 100%

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#640]
Ironjaw Humor does not drop 100%
![image](https://user-images.githubusercontent.com/71927836/99784992-8cd74780-2b57-11eb-8f41-300e799bc0de.png)
In addition, there are two Ironjaw Behemoth at the Area.
https://www.wowhead.com/quest=26823/too-big-for-his-britches

**Comment by Serithul** [comment]
https://www.wowhead.com/item=60380/ironjaw-humour it shouldn't drop 100%

**Comment by acidmanifesto** [comment]
Patch is sent in with the appropiate %. will be live in the next restart
