### ISSUE TITLE
[Services][Npcs]Game Crash at bambala flight master.

### ISSUE THREAD

**Issue by KCorruption** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#651]
**Describe the bug**
- This can be deleted.

**Comment by KCorruption** [comment]
This also happens with the flight master "Skymistress Gloaming - 16192" in Eversong Woods, near the entrance of Silvermoon. The suspected reason the crash occurs is due to a memory leak generated as a result of these flightmasters in particular going straight into their "Flight Map" page instead of having option/text dialogue before hand.

**Comment by acidmanifesto** [comment]
Close this
