### ISSUE TITLE
Scaling stopped working in the Arathi Highlands

### ISSUE THREAD

**Issue by bobacaric2** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#652]
**Describe the bug**
In the drywhisker Gorge the mobs are level 28 while i was level 40. 

**To Reproduce**
1. Go to 'Arathi Highlands - Hammerfall and right above there is a cave called Drywhisker Gorge, in it there are kobolds which are lower level than those outside. Also it seemed that the scaling stopped with the amount of EXP from quests. I get the double amount of weekend bonus but not the x5 from what the quests should be worth. Checked the amount of exp on Gamepedia and Wowhead. 

**Expected behavior**
I am not sure, i think the scaling should work in cave too, and the amount of exp scaling stopped working after the Database got rolled back.

**Screenshots**
http://prntscr.com/vnj68l

**Comment by bobacaric2** [comment]
Also EXP from quests stopped working too i think, i would get double exp from weekend deal but Not the x5 from quest amount. Note: This happened after database reroll, i think before it, the scaling was okay, though before i didn't go in the cave so i can't be sure about levels.

**Comment by Serithul** [comment]
Zone scaling addressed a couple of months ago. Closing.
