### ISSUE TITLE
[Artifact Quest] Outlaw Rogue, Final Stage Claiming the Prize Boss

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#666]
Boss Dread Admiral Eliza's mechanic where she casts Musket Barrage is Instant and kills me instantly.
![image](https://user-images.githubusercontent.com/71927836/100091704-f0cb7a00-2e8f-11eb-8334-b96aac1d8cea.png)
https://www.wowhead.com/npc=102293/dread-admiral-eliza
https://www.wowhead.com/quest=40849/the-dreadblades#

**Comment by acidmanifesto** [comment]
this was patched a few months ago. please close
