### ISSUE TITLE
The champion of Anguish quest in Zul drak

### ISSUE THREAD

**Issue by bobacaric2** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#667]
**Describe the bug**
When the quest is started, the boss spawns in the middle of the arena, but it spawns around 20+ of them, enough that my fps dropped. 

**To Reproduce**
Take the quest in dalaran for zul'drak arena and follow the questline until the last one
1. Go to '47.8;56.3 coords on map and take the quest there and take a look

**Expected behavior**
It should spawn only one, not 20+ of them... :D 

**Screenshots**
http://prntscr.com/vr8v50

**Comment by acidmanifesto** [comment]
711 were spawned. a patch has been made and will be live in the next restart
