### ISSUE TITLE
Mage Blink skill not working properly

### ISSUE THREAD

**Issue by bobacaric2** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#669]
**Describe the bug**
Blink doesn't push/teleport you forward instead it makes you just jump in place.

**To Reproduce**
Create a mage and get a Blink

**Expected behavior**
Should port you forward for certain range

**Screenshots**
http://prntscr.com/vs01nt

**Comment by sausagemadness** [comment]
Marking Duplicate : https://github.com/Project-AuroraWoW/Project-Aurora/issues/523
