### ISSUE TITLE
Quest Away From Prying Eyes (44782)

### ISSUE THREAD

**Issue by voctavio** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#680]
**Describe the bug**
There is an Artifact Quest chain that starts at 
https://www.wowhead.com/quest=46765/the-broken-shore-investigating-the-legion
And the 2nd to last quest 
https://www.wowhead.com/quest=44782/away-from-prying-eyes
There is suppose to be a portal that opens up to go to the Purple Parlor, but nothing happens after starting the quest. And cannot turn in quest either as it is a zoned phased quest to lead into 
https://www.wowhead.com/quest=44821/in-dire-need

**To Reproduce**
1. Go to 'Archmage Khadgar
2. Click on 'Away from Prying Eyes'
3. NPC's should walk up the stairs, and portal should open to Purple Parlor. 
4. No Portal opens, and nothing else finishes. 

**Expected behavior**
 NPC's should walk up the stairs, and portal should open to Purple Parlor.

**Comment by acidmanifesto** [comment]
patch sent in
