### ISSUE TITLE
[Raid]Antorus, Burning Throne, Argus, The Unmaker Skill 

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#682]
Skill "End of all Things" is either instant cast or channeling bar is not showing. 
I was with a friend doing Argus and we got to phase 4 where we resurrected with Gift of the Lifebinder, a few moments later, we were suddenly instant wiped. 
Only thing that can wipe us is the skill "End of all things" and we didn't see him cast it.
We tried to kill him for 2 tries again but we still got wiped.
https://www.wowhead.com/spell=256544/end-of-all-things

**Comment by acidmanifesto** [comment]
This was addressed and fix in janurary i beleive.

**Comment by Serithul** [comment]
Closing,
