### ISSUE TITLE
[Raid]Antorus, Burning Throne, Argus, The Unmaker Loot

### ISSUE THREAD

**Issue by Madladdle** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#686]
Loot Chest after defeating Argus, The Unmaker is missing at the Vindicaar Instance after defeating Argus.
Due to this I was unable to get Loot for defeating Argus.

**Comment by acidmanifesto** [comment]
I will look into this. But if i recall right this loot chest triggers with a party as it uses some form of the mythic handler system.

**Comment by Fransango** [comment]
If i am not wornt this is the id of the chest

https://www.wowhead.com/object=277355/the-pantheons-bounty

**Comment by acidmanifesto** [comment]
Fixed . @sausagemadness @Madladdle  please close. Compile sent in to joey and serithul

**Comment by Serithul** [comment]
Server updated, the fix is now live.
