### ISSUE TITLE
major [Monk.Windwalker.Talent] Chi Orbit doesn't function

### ISSUE THREAD

**Issue by JerichoPride** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#711]
Chi Orbit appears to be doing nothing.

**To Reproduce**
1. Chose Chi Orbit Talent
2. No orbs are spawning

**Expected behavior**
Every few seconds an orbs should start gravitating around the character up to a maximum of 4 orbs . When in proximity of a few yards of an enemy, they should collide with it , do damage and disappear.

**Additional context**
I can hear the sound of orbs being created.

**Comment by acidmanifesto** [comment]
Was fixed a few months ago i believe.
