### ISSUE TITLE
[Monk.Windwalker.Skill] Strike of the Windlord + "Storm,Earth and Fire"

### ISSUE THREAD

**Issue by JerichoPride** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#716]
**Describe the bug**
"Strike of the Windlord" is not used by the clones when activating "Storm,Earth and Fire" skill.

**To Reproduce**
1. Cast Storm,Wind and Fire near a target(ex dummy in Shrine of the Two Moons)
2. Use "Strike of the Windlord" while clones are attacking your target.
3. There is no animation from the clones and only your damage is showing.

**Expected behavior**
Strike of the Windlord should be used by the clones from Storm,Earth and Fire.

**Comment by acidmanifesto** [comment]
Issue was fixed in feburary.
