### ISSUE TITLE
Sen'jin village in Durotar misses his inkeeper

### ISSUE THREAD

**Issue by liangna23** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#719]
heya !

I'm looking for the inkeeper in this village because i'm on rate x1 and so i do all quests everywhere.

Can you have a look at it please ?

Thanks a lot.

**Comment by Serithul** [comment]
From a search i did, i found out Sen'jin Village doesn't have an innkeeper. Do you have any source that says otherwise ?

**Comment by liangna23** [comment]
No sorry I thought i'd find one as in every village of WOW but i was wrong ;(
thanks for looking though =)
