### ISSUE TITLE
[Low Priority] Imp minions in Dustwind Cave, near Orgrimmar

### ISSUE THREAD

**Issue by liangna23** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#720]
heya !

Have to kill Burning Blade men in this cave but cultists' minion seem to have higher level than expected for this area.

![WoWScrnShot_020521_085750](https://user-images.githubusercontent.com/78547601/107005857-9bb1bb80-6790-11eb-83ac-2e4ea741e95b.jpg)

can't use cartographe to be sure this isn't right and informations on wowhead aren't much helpfull either so hope i won't waste your time this time again asking you to have a look at this.

**Comment by TheDdraig** [comment]
This has now been fixed, thanks for your report.
