### ISSUE TITLE
Legion fishing, rares item isnt in loot table

### ISSUE THREAD

**Issue by Fransango** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#724]
https://en.wowhead.com/item=133701/u%C3%B1a-del-pie-de-skrog

https://en.wowhead.com/item=133703/caracola-perlescente

https://en.wowhead.com/item=133704/broche-de-pez-reina-oxidado

https://en.wowhead.com/item=133705/raspa-podrida

https://en.wowhead.com/item=133708/hojacardo-ahogado

https://en.wowhead.com/item=133707/reptanoches-de-pesadilla

Quest giver item
https://en.wowhead.com/quest=40960/perla-luminosa

**Comment by Serithul** [comment]
Fixed
