### ISSUE TITLE
Supreme lord kazzak

### ISSUE THREAD

**Issue by Fransango** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#735]
This world boss of draenor its bug. Seri cant see the boss.

https://es.wowhead.com/npc=94015/se%C3%B1or-supremo-kazzak

**Comment by acidmanifesto** [comment]
Patch submitted to @Serithul .

**Comment by acidmanifesto** [comment]
Patch sent in earlier today. Forgot to mention it here. Please Close

**Comment by Fransango** [comment]
CLOSED
