### ISSUE TITLE
Molten core pet from golemagg boss

### ISSUE THREAD

**Issue by Fransango** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#742]
![imagen](https://user-images.githubusercontent.com/35998435/108562888-dbd07c80-7300-11eb-86d8-0d7270e91654.png)
it dont unlock the pet

![imagen](https://user-images.githubusercontent.com/35998435/108562925-ebe85c00-7300-11eb-9ef5-d755a2f24ddc.png)

**Comment by acidmanifesto** [comment]
Current drop rate for item 93035 is 20% as per wowhead.
https://www.wowhead.com/item=93035/core-of-hardened-ash
Item is verified in the creature loot table.
Item is working and does teach Ashstone Core
No issue besides it being a 20% drop rate which is wowhead accurate.

**Comment by Fransango** [comment]
Yep it drop the item, but i used that and dont unlock the pet
![imagen](https://user-images.githubusercontent.com/35998435/108628767-f881c700-745c-11eb-90fb-cf82d6715a0a.png)

Maybe it work and i had a glich or lagg issue and it dont work for me. I will farm more times molten core for tramg and i will see

**Comment by Fransango** [comment]
![imagen](https://user-images.githubusercontent.com/35998435/108630544-95486280-7465-11eb-8101-445a2cddca17.png)
I looted it, and it unlock ashstone core no corefire imp

**Comment by acidmanifesto** [comment]
Patch is sent in. Both items should work whenever the patch goes live. If you consumed the item already then they should be in your inventory.

**Comment by Serithul** [comment]
Fix is live. Please test and let us know if everything's good.

**Comment by Fransango** [comment]
I have yet both pet. Another player did the intance and get 1 of the items, and he told me, that the item work now.
I farmed it again for check myself (both items) and dont unlock a second pet of each type.
![imagen](https://user-images.githubusercontent.com/35998435/108822307-2ed75780-75bf-11eb-8f9d-c828dfc1974c.png)

**Comment by acidmanifesto** [comment]
issue has been resolved. please clost
