### ISSUE TITLE
Fenryr tameable dont spawn

### ISSUE THREAD

**Issue by Fransango** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#757]
Hunter can tamer fenryr on mytic dificulty. 
For this you need kill solo on mytic the boss and then the tameable version will spawn in the cave

![imagen](https://user-images.githubusercontent.com/35998435/109019324-2d8a5580-76b9-11eb-98b0-3f3c31329005.png)

Min 4:20+
https://www.youtube.com/watch?v=Oe1LK5cOU_c

**Comment by acidmanifesto** [comment]
Patch sent in. Fenryr is now spawning after Fenryr death and is tamable. will be live in the next restart
