### ISSUE TITLE
Bag 141159/141169, infinite loop 

### ISSUE THREAD

**Issue by Fransango** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#771]
Every use of the bag give another bag. The first bag was the reward of heroic eye of azhara finder dungeon. This first bag droped 2 bags.

![imagen](https://user-images.githubusercontent.com/35998435/111051467-8563e300-8453-11eb-885e-27a7548f2b5c.png)
![imagen](https://user-images.githubusercontent.com/35998435/111051477-8f85e180-8453-11eb-9278-e78c79928577.png)

There is 2 id, every one loot the other: 
-141159 give 141169
-141169 give 141159
2 Bags from the first bag:
![imagen](https://user-images.githubusercontent.com/35998435/111051490-b2b09100-8453-11eb-86f2-2fe527557744.png)

**Comment by acidmanifesto** [comment]
Noice...

**Comment by acidmanifesto** [comment]
Patch sent in

**Comment by Fransango** [comment]
Fixed
