### ISSUE TITLE
Second artifact quest of warlock enabled for all classes

### ISSUE THREAD

**Issue by Fransango** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#781]
https://www.wowhead.com/quest=43984/the-tome-opens-again

![imagen](https://user-images.githubusercontent.com/35998435/112657320-98fb4a80-8e52-11eb-9deb-269e55dc4654.png)

**Comment by Fransango** [comment]
The quest for other clases end and dont give more quests only 5g. Minor bug.

**Comment by acidmanifesto** [comment]
good fine. patch has been sent in
