### ISSUE TITLE
Missing Quest Starter Item

### ISSUE THREAD

**Issue by phantom1004** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#787]
Surveyor Candress (16522) on death should drop "Blood Elf Plans" (24414) with 100% drop rate

**Comment by phantom1004** [comment]
https://www.wowhead.com/npc=16522/surveyor-candress
https://www.wowhead.com/item=24414/blood-elf-plans

**Comment by joey2801** [comment]
fixed <3
