### ISSUE TITLE
Quest Starting Item: Rune Covered Tablet

### ISSUE THREAD

**Issue by phantom1004** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#791]
Quest Starting Item "Rune Covered Tablet" (23759) Dropped by Wrathscale Myrmidon, Wrathscale Naga and Wrathscale Siren (17194,17193 and 17195 respectively) should have an extremely higher drop rate then noted on wowhead/on the database. It is also tied to the required completion of a quest which also has an issue. Bug Report link to follow in comments

https://www.wowhead.com/item=23759/rune-covered-tablet
https://www.wowhead.com/npc=17194/wrathscale-myrmidon
https://www.wowhead.com/npc=17193/wrathscale-naga
https://www.wowhead.com/npc=17195/wrathscale-siren

**Comment by joey2801** [comment]
fixed :)
