### ISSUE TITLE
Quest: A Small Start

### ISSUE THREAD

**Issue by phantom1004** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#792]
Unlike what Wowhead would like us to believe, quest "A Small Start" (9506) should be acceptable as soon as the level requirement is met.

Additional Evidence https://youtu.be/ZGKw0-WTlKM?t=848

https://www.wowhead.com/quest=9506/a-small-start

**Comment by joey2801** [comment]
fixed :)
