### ISSUE TITLE
Quest Starting Item: Faintly Glowing Crystal

### ISSUE THREAD

**Issue by phantom1004** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#793]
Quest Starting Item "Faintly Glowing Crystal" (23678) dropped from "Infected Nightstalker Runt" (17202) should be higher then currently set? From experience (Source:Trust me bro) i recall this item dropping after the first kill every time

https://www.wowhead.com/item=23678/faintly-glowing-crystal
https://www.wowhead.com/npc=17202/infected-nightstalker-runt

**Comment by joey2801** [comment]
fixed :)
