### ISSUE TITLE
Quest Item: Pile of Leaves

### ISSUE THREAD

**Issue by phantom1004** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#794]
Quest Item "Pile of Leaves" (23791) Lootable from Pole of Leaves <Object> (181697) should have a 100% drop chance without chance to fail

https://www.wowhead.com/object=181697/pile-of-leaves
https://www.wowhead.com/item=23791/pile-of-leaves

**Comment by joey2801** [comment]
fixed :)
