### ISSUE TITLE
Quest Item: Gurf's Dignity

### ISSUE THREAD

**Issue by phantom1004** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#795]
Random Mob "Murgurgula" (17475) is supposed to drop item "Gurf's Dignity" (23850) at a near 100% drop rate

https://www.wowhead.com/item=23850/gurfs-dignity
https://www.wowhead.com/npc=17475/murgurgula

**Comment by joey2801** [comment]
Fixed :)
