### ISSUE TITLE
Quest Mob: The Kurken

### ISSUE THREAD

**Issue by phantom1004** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#796]
Quest Mob "The Kurken" (17447) is supposed to drop " The Kurken's Hide" (23860) with 100% drop chance

https://www.wowhead.com/npc=17447/the-kurken
https://www.wowhead.com/item=23860/the-kurkens-hide

**Comment by acidmanifesto** [comment]
Patch is made and will be live in the next restart
