### ISSUE TITLE
Quest Item: Arcane Core

### ISSUE THREAD

**Issue by phantom1004** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#798]
During quest "Major Malfunction" (8472) "Arcane Patroller" (15638) are supposed to drop "Arcane Core" (21808) however during gameplay the mob does not register as a "quest mob" and does not drop anything.

https://www.wowhead.com/item=21808/arcane-core
https://www.wowhead.com/npc=15638/arcane-patroller
https://www.wowhead.com/quest=8472/major-malfunction

**Comment by joey2801** [comment]
must've been unlucky :(
tested my end although it doesn't register as a quest mob (for whatever reason) the quest item does drop <3
