### ISSUE TITLE
Quest Start Item: Captain Kelisendra's Lost Rutters

### ISSUE THREAD

**Issue by phantom1004** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#799]
Grimscale Murlocs "Grimscale Forager/Oracle/Murloc/Seer" and "Mmmrrrggglll" (15670/15669/15668/15950/15937) are supposed to have a high chance (in my experience) to drop the quest starter item as it is a fundamental part of the Eversong Woods Questline

https://www.wowhead.com/item=21776/captain-kelisendras-lost-rutters
https://www.wowhead.com/npc=15670/grimscale-forager
https://www.wowhead.com/npc=15669/grimscale-oracle
https://www.wowhead.com/npc=15668/grimscale-murloc
https://www.wowhead.com/npc=15950/grimscale-seer
https://www.wowhead.com/npc=15937/mmmrrrggglll
"In my experience" Source: Trust Me Bro

**Comment by phantom1004** [comment]
Post Report Message, All quest completion requirements for this item to drop need to be removed, making only a player level restriction the only restriction

**Comment by joey2801** [comment]
fixed :)
