### ISSUE TITLE
Quest Starting Item: Incriminating Documents

### ISSUE THREAD

**Issue by phantom1004** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#800]
Quest Starting Item "Incriminating Documents" (20765) should have a near if not 100% drop chance from "Darnassian Scout" (15968) (in my experiences) as it is part of the entire quest chain of Eversong Woods

https://www.wowhead.com/npc=15968/darnassian-scout
https://www.wowhead.com/item=20765/incriminating-documents
"in my experiences" Source:Trust Me Bro

**Comment by phantom1004** [comment]
Post Report Message, All quest completion requirements for this item to drop need to be removed, making only a player level restriction the only restriction

**Comment by joey2801** [comment]
fixed :)
