### ISSUE TITLE
Quest Item: Chieftain Zul'Marosh's Head

### ISSUE THREAD

**Issue by phantom1004** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#809]
Upon killing "Chieftain Zul'Marosh" (15407) his head "Chieftain Zul'Marosh's Head" (20760) should be a 100% drop rate as it is required for quest "Zul'Marosh" (8479)

https://www.wowhead.com/item=20760/chieftain-zulmaroshs-head
https://www.wowhead.com/npc=15407/chieftain-zulmarosh
https://www.wowhead.com/quest=8479/zulmarosh

**Comment by acidmanifesto** [comment]
patch is made and will be live in next restart
