### ISSUE TITLE
NPC: Val'kyr Battle-maiden

### ISSUE THREAD

**Issue by phantom1004** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#836]
Its hard for me to take this one seriously so i apoligise!

"Val'kyr Battle-maiden" (AKA LAZY BITCH) "28534" is supposed to ress yo ass if you die. she appears, casts revive on you (that doesnt revive you btw) then fucks off! SCAMMED!

Ally:Gnome:DK

https://www.wowhead.com/npc=28534/valkyr-battle-maiden

**Comment by acidmanifesto** [comment]
Fixed. Patch is being sent in now to aurora

**Comment by acidmanifesto** [comment]
i cant close this ticket. so feel free to close it.
