### ISSUE TITLE
Professions : issue affects some classes

### ISSUE THREAD

**Issue by NovaFujiwara** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#841]
in the spell book General Tab some classes have professions somehow showing like this it shouldn't happen usually but i think its an issue when u boost ur professions using the shop tool. tho strangely this didn't happen on my warrior but did happen on my Demon Hunter & Hunter Names : Cosmic & Fujiwara. my warrior that isn't affected is Nova !

Professions shouldn't be showing in your spell book General its made for ''General'' stuff the profession has its own Tab. ^^

**Here's some screenshot of the issues :** 

![General Tab 2](https://user-images.githubusercontent.com/83447382/116674251-131c7300-a9ad-11eb-8118-80a64d7445c4.png)
![Professions](https://user-images.githubusercontent.com/83447382/116674257-14e63680-a9ad-11eb-96c1-80ca090286c4.PNG)
![General Tab 1](https://user-images.githubusercontent.com/83447382/116674261-16176380-a9ad-11eb-8254-db784cbadb9c.png)

**Comment by NovaFujiwara** [comment]
Nova = Void Elf. Alliance. Warrior.
Cosmic = Blood Elf. Horde. Demon Hunter.
Fujiwara = Void Elf. Alliance. Hunter.

**Comment by acidmanifesto** [comment]
Issue was fixed about a month ago. i wasnt aware there was a issue was put in on it, so i do apologize for the late response.. now if you still have those skills please contact a gm to correct it. thank you for the report
