### ISSUE TITLE
Demon Hunter - Havoc issue : wrong Leech %

### ISSUE THREAD

**Issue by NovaFujiwara** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#843]
Having https://www.wowhead.com/spell=191427/metamorphosis on should give you 30% Leech but its giving 12%
Proof :
![30%](https://user-images.githubusercontent.com/83447382/116682429-e79e8600-a9b6-11eb-94f8-d5f96ffdd8e1.png)
![12%](https://user-images.githubusercontent.com/83447382/116682440-ed946700-a9b6-11eb-8538-15ea15f700a3.png)

Having https://www.wowhead.com/spell=204909/soul-rending on should give you 100% Leech but its giving 40%
Proof :
![40%](https://user-images.githubusercontent.com/83447382/116682714-48c65980-a9b7-11eb-8610-c4d21aafce6f.png)
![100%](https://user-images.githubusercontent.com/83447382/116682733-4ebc3a80-a9b7-11eb-88d1-7ed27da990e6.png)

**Comment by acidmanifesto** [comment]
the 30% was introduced in bfa 801, not legion.
