### ISSUE TITLE
NPC: Scarlet Miners

### ISSUE THREAD

**Issue by phantom1004** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#846]
NPC "Scarlet Miners" (28819) are correctly labeled as "Hostile" however they should not attack the player unless attacked first

Ally:Gnome:DK

https://www.wowhead.com/npc=28819/scarlet-miner

**Comment by acidmanifesto** [comment]
i had to get with a few tc developers themselves, they told me it is correct currently as they are all hostile to both alliance and horde players regardless of dk class or not.
