### ISSUE TITLE
Quest/Gossip: How to Win Friends and Influence Enemies

### ISSUE THREAD

**Issue by phantom1004** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#850]
During quest "How to Win Friends and Influence Enemies" (12720) you are given a set of "Keleseth's Persuader" (39371) which should cause the target (when effected by the debuff) (Couldnt find debuff # sorry) to Gossip/Emote Vocally when effected, the % on the server currently seems so low that when i did the quest i did not notice the emote/Gossip even once (However MDic reassures me that the reaction is indeed scripted

Ally:Gnome:DK

https://www.wowhead.com/quest=12720/how-to-win-friends-and-influence-enemies

**Comment by acidmanifesto** [comment]
even on wow head and forums every all agrees the chance is brutal. it is accomplishable on the server. I banged out 40 scarlets before it triggered. it is based on a low % as it is with blizzard.
