### ISSUE TITLE
Pandaria faction shrines. Portal to capitals enabled for all factions

### ISSUE THREAD

**Issue by Fransango** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#855]
On shrines of 7 stars and 2 moons portal to capitals (ogrimar, silvermoon etc) can be used for ali chars, and surely same for ali portals w horde chars.

**Comment by acidmanifesto** [comment]
Well i am looking into several hard references and several sites and dbc file verifications, it all shows that none of those portals are actually faction locked. Usually they are hidden behind phases such as ebon hold in the dk starter area. So at this point we will have to say this isnt a issue until further evidence points to other wise.
