### ISSUE TITLE
[Quest] Item does not drop

### ISSUE THREAD

**Issue by TheVoidstar** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#858]
Quest Harnessing-power
https://www.wowhead.com/quest=45398/harnessing-power
Mission item does not drop from quest mob. Said Mob does not drop any items.

https://www.wowhead.com/npc=116827/andjor-dragontamer Should drop https://www.wowhead.com/item=143676/rimefangs-harness 99% of the time.

**Comment by acidmanifesto** [comment]
Patch is made and will be live in next restart
