### ISSUE TITLE
NPC: Crypt Walker

### ISSUE THREAD

**Issue by Noodlerogue88** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#860]
NPC "Crypt Walker" (8556) is incorrectly giving rep

Horde:Belf:Mage

https://www.wowhead.com/npc=8556/crypt-walker

**Comment by acidmanifesto** [comment]
Rep reward is correct with that npc kill. You can kill undead mobs in the Eastern and Western Plaguelands to gain reputation with the Argent Dawn. Each kill results in 10 reputation points.
