### ISSUE TITLE
Quest Item: Living Rot

### ISSUE THREAD

**Issue by Noodlerogue88** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#867]
During quest "To Kill with Purpose" (27451) you are required to collect "7" "Living Rot" (15447) from mobs (see below for ID's) however in my experience of clearing the entire camp 5 times i didn't have a single one to drop and had to resort to competing the quest in Orgrimmar

Horde:Belf:Mage

https://www.wowhead.com/quest=27451/to-kill-with-purpose
https://www.wowhead.com/item=15447/living-rot
https://www.wowhead.com/npc=8538/unseen-servant
https://www.wowhead.com/npc=8541/hate-shrieker
https://www.wowhead.com/npc=8531/gibbering-ghoul
https://www.wowhead.com/npc=8543/stitched-horror
https://www.wowhead.com/npc=8525/scourge-warder
https://www.wowhead.com/npc=8526/dark-caster
https://www.wowhead.com/npc=45851/overstuffed-golem

**Comment by acidmanifesto** [comment]
Patch is made and will be in the next restart
