### ISSUE TITLE
NPC: Rimblat Earthshatter

### ISSUE THREAD

**Issue by Noodlerogue88** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#871]
While questing "Rimblat Earthshatter" (16134) should be found at Lights Hope Chapel (EPL) however he is no where to be seen, his exact location (cords) can be found in the link below

Horde:Belf:Mage

https://www.wowhead.com/npc=16134/rimblat-earthshatter

**Comment by acidmanifesto** [comment]
![image](https://user-images.githubusercontent.com/16887899/121244284-ada18900-c86c-11eb-8600-111aa36922f7.png)
He is present when u do the whole entirely of Fiona's Caravan.
