### ISSUE TITLE
NPC: Lights Hope Chapel FP

### ISSUE THREAD

**Issue by Noodlerogue88** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#873]
The Lights Hope Chapel FP are usable by both factions

**Comment by acidmanifesto** [comment]
FP?

**Comment by acidmanifesto** [comment]
so FP meaning Flight Path. Lights Hope Chapel is nuetral ground. In earlier expansions the two flight managers were faction specifics. while after cata, they became nuetral and able to be used by both horde and alliance. Although having two literally right next to each other is redundent, it is in line with blizzard.
