### ISSUE TITLE
Heroic dungeon escape from durnholde boss drops 

### ISSUE THREAD

**Issue by Badjourasmix** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#874]
The following bosses in the heroic dungeon escape from durnholde don't seem to drop any gear:
https://www.wowhead.com/npc=17862/captain-skarloc
https://www.wowhead.com/npc=18096/epoch-hunter
This boss seems to drop some gear but it drops the normal version and not the heroic mode:
https://www.wowhead.com/npc=17848/lieutenant-drake

**Comment by acidmanifesto** [comment]
All drop rates are correct. just low.
