### ISSUE TITLE
Quest: The Headmistress' Keys (LEGION)

### ISSUE THREAD

**Issue by Noodlerogue88** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#875]
During quest "The Headmistress' Keys" (37730) the objective is to collect the "Tidestone Vault Key" (120169) from "Elya Azuremoon" (88859).

This quest item is supposed to be a 100% Drop Chance.

Class/Race/Faction currently unknown 

https://www.wowhead.com/quest=37730/the-headmistress-keys
https://www.wowhead.com/npc=88859/elya-azuremoon
https://www.wowhead.com/item=120169/tidestone-vault-key

**Comment by Noodlerogue88** [comment]
Horde:Belf:Warlock

**Comment by acidmanifesto** [comment]
Item is set to 100%. Patch will be sent in
