### ISSUE TITLE
Quest : Making the World Safe for Profit

### ISSUE THREAD

**Issue by Robibibi** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#876]
The "Deal with Queen Kraklaa" part of the "Making the World Safe for Profit" (37657) quest doesn't validate on the Queen's death.

You're supposed to encounter Queen Kraklaa (89287) along with a monster called Oublion (89350), but only the Queen is to be found.
Here's the normal encounter : 

"There are two mobs located: Queen Kraklaa and Oublion. Attack Oublion first, when he goes invulnerable, switch to Queen Kraklaa. Slay her and then defeat Oublion."
The quests confirms the "Deal with Queen Kraklaa" objective after Oublion dies.

https://www.wowhead.com/quest=37657/making-the-world-safe-for-profit

![image](https://user-images.githubusercontent.com/85083336/120122767-2a689f00-c1ab-11eb-8df2-cd0b178e97b1.png)

**Comment by acidmanifesto** [comment]
patch was sent in on a simular matter with this quest. should be live in the next restart.
