### ISSUE TITLE
Hostile 110 Lost Spectral Gryphon in Stormwind

### ISSUE THREAD

**Issue by DMCK96** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#877]
There is a hostile level 110 'Lost Spectral Gryphon' spawned at the Stormwind Gryphon Master on the custom realm. Preventing alliance characters from using gryphon master or riding training in Stormwind.

**Comment by acidmanifesto** [comment]
ah ok. thats on me. i am going to make a patch to make it nuetral

**Comment by acidmanifesto** [comment]
![image](https://user-images.githubusercontent.com/16887899/120565205-8cf3b200-c3da-11eb-80fc-968cbae5b32b.png)
Ok. i made it nuetral, same with the orgrimmar counter part Gon. I will send in the patch for aurora to apply it tomorrow. thanks for the report. that was definately on me. They were special pets for hunters to tame when they are level 110.

**Comment by Serithul** [comment]
Fix pushed. Will be live on the next restart.
