### ISSUE TITLE
Lightforged Draenei - Spawning without riding and starter mount

### ISSUE THREAD

**Issue by DMCK96** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#878]
Lightforged Draenei spawn at level 20 without knowing riding nor knowing their starter mount.

**Comment by acidmanifesto** [comment]
Correct. If u dont have the original requirements u wont start with it. However we have a alliance start module to give them the required stuff. This is most like turned off. @Serithul can u confirm this at you convenience?

**Comment by Serithul** [comment]
Indeed. We have the races unlocked by default, but we haven't enabled the mount acquisition from the get go. You'll have to grind the achievements to get their mounts. This is not a bug.
