### ISSUE TITLE
Quest "Helboar, the Other White Meat"

### ISSUE THREAD

**Issue by sanvenganza2** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#883]
**Describe the bug**
Helboars do not drop Tainted helboar meat in order to purify. Have been killing them for 30 minutes and not a single drop.

**To Reproduce**
1. Kill any Helboar.

**Expected behavior**
https://tbc.wowhead.com/quest=9361/helboar-the-other-white-meat

**Comment by acidmanifesto** [comment]
Patch has been sent in, will be live in the next update. Thank you for the report.
