### ISSUE TITLE
Wrong reputation possibly.

### ISSUE THREAD

**Issue by sanvenganza2** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#884]
**Describe the bug**
When doing the hellfire citadel dungeons, all of them give "Honor hold" reputation, Shattered halls also gives other kinds of reputation like the "Huojin pandaren" besides Honor hold. Also when out of the dungeons and you kill any orc near the citadel, they give honor hold rep too. 10 per kill. I don't know if this is a bug or not but i am reporting it anyway.

**Comment by acidmanifesto** [comment]
As odd as it sounds. the reputations are correct with the mobs, reconfirming with both sniffs and wowhead database as well for the numerous npcs that are present was a bit time consuming but needed to ensure myself it was correct as well. now as for the honor being gained, thats the honor for killing of elite and boss module, traditionally honor is only given for pvp action, however with low population, this module is turned on to give the player the ability to still gain honor.
