### ISSUE TITLE
Quest "make them listen" ID:10220

### ISSUE THREAD

**Issue by sanvenganza2** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#886]
**Describe the bug**
The NPC that gives the quest is missing or hidden to normal players. Name of the NPC is "Emissary Mordiba". Quest tag appears on map but in the camp there is no visible NPC to get the quest from. NPC must be located at stonebreaker post just beside "Althen the historian". 

**Expected behavior**
https://www.youtube.com/watch?v=QLNJircl3jQ

**Comment by acidmanifesto** [comment]
issue fixed by @skeezerbean and patch will be live at the next restart.
