### ISSUE TITLE
Quest "The Defense of Warsong Hold" ID:11596

### ISSUE THREAD

**Issue by sanvenganza2** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#887]
**Describe the bug**
High overlord saurfang missing or hidden to normal players. Can't get the quest.

Expected location of Saurfang:
![image](https://user-images.githubusercontent.com/48453990/123165585-b69d7780-d474-11eb-8256-62e6d6923a9a.png)

Quest details:
https://www.wowhead.com/quest=11596/the-defense-of-warsong-hold#see-also

Expected behaviour:
https://www.youtube.com/watch?v=hJWFExELx8c

**Comment by skeezerbean** [comment]
The NPC is there, but the display ID isn't working and makes him invisible. Sending a fix to MDic shortly
