### ISSUE TITLE
Quest "A Lesson in Fear" ID: 11282

### ISSUE THREAD

**Issue by sanvenganza2** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#890]
**Describe the bug**
The 3 NPC's that should spawn by killing "Winterskorn defenders" do not spawn. They normally should spawn after 5-10 kills top. Killed over 30 and not a single one spawned. Their names are "Oric the Baeful, Ulf the Bloodleter, Gunnar Thorvardsson"

**Expected behavior**
https://www.wowhead.com/quest=11282/a-lesson-in-fear#comments

**Additional context**
https://www.youtube.com/watch?v=D5cmNfyejZE

**Comment by acidmanifesto** [comment]
Fix was applied. Thank you.
