### ISSUE TITLE
Karazhan Raid

### ISSUE THREAD

**Issue by Badjourasmix** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#891]
In the Karazhan 10 man raid the boss Attumen the Huntsman doesn't drop any loot. I've been doing this raid for a month now and every time I kill him he doesn't drop anything which makes it impossible to farm the mount Fiery Warhorse's Reins (https://tbc.wowhead.com/item=30480/fiery-warhorses-reins), Also there is no chess event so any loot from that is not available to the player.

**Comment by acidmanifesto** [comment]
looking it over right now. the drop rate is at 1% and is working. Drop rates is consistent with sniffs and also wowhead as well.
