### ISSUE TITLE
Chunk of horn item

### ISSUE THREAD

**Issue by bobacaric2** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#892]
The item i got in Azsuna by killing some mobs. Now i do not know if this is specific class related item or not, but since it does give a quest and there are no obvious limitations as to who can take it, i deduced that it is for everyone. When i click on the item, the item says in the chat: Skill, nothing else. Look at the picture. 

https://prnt.sc/1bxwc5g

**Comment by acidmanifesto** [comment]
That is a interesting one. Do u have the mining skill by chance? If so what level? The item requires mining.

**Comment by acidmanifesto** [comment]
I will push a update to aurora shortly so it can elaborate more detail of the disqualifier your character is encountering.

**Comment by bobacaric2** [comment]
Thank you. No mining. No professions. Thought it was just a random drop from a mob and it has a Q :D
