### ISSUE TITLE
[Quest] Control Orb didnt drop from the Mob

### ISSUE THREAD

**Issue by Trayline** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#893]
https://www.wowhead.com/quest=40745/shift-change

in this quest, the item Control Orb (quest item) drop rate is 100%. But after i kill the NPC it didnt drop
The orb is the item to free the little Nightborne, from the barrier

**Comment by acidmanifesto** [comment]
Thank you for the report. patch has been sent in to aurora. It will reflect on the next restart.
