### ISSUE TITLE
[Quest] Siren Blood didnt drop from the Mobs

### ISSUE THREAD

**Issue by Trayline** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#894]
https://www.wowhead.com/quest=40334/fishermans-tonic
The item Siren Blood is 100% drop rate, but after i kill the NPC and wait for her respawn (around 3 times) the item didnt drop at all

Blood Elf, Paladin

**Comment by acidmanifesto** [comment]
Thank you for the report. patch has been sent in to aurora. It will reflect on the next restart.
