### ISSUE TITLE
[quest] starting area lightforged draenei

### ISSUE THREAD

**Issue by vikingjunior** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#896]
**Describe the bug**
when you go into the first mission in the starting area, the mobs are at a skull lvl with vast amounts of health, and one shotting you

**To Reproduce**
1. make new lightforged
2. Go outside cave to first lightforged draenei starting scenario

**Expected behavior**
mobs at my lvl (20)

**Screenshots**

**Additional context**
![2021-09-24 11_54_31-World of Warcraft](https://user-images.githubusercontent.com/25037895/134656606-ba4e5ecd-3c39-45fa-b47a-33a24777e6f7.jpg)

**Comment by acidmanifesto** [comment]
![image](https://user-images.githubusercontent.com/16887899/134686833-2779369d-55a9-46e9-b7fa-a886436126fd.png)
I am a bit confused. All allied races first quest is to report to their ambassadors of their respected faction at their respected capitals. The first quest for the LF Draes is to goto stormwind where the portal is on the lower deck where you would then turn into ambassador moorgard. Which then follows you up with the quest Stranger in a Strange Land which is where you would goto the hero's board in stormwind.
![image](https://user-images.githubusercontent.com/16887899/134686962-84f6e5e9-ceef-44b6-b586-af8364fca6df.png)
Leaving the ship at the tele pad would put u in a scenario that is reserved for the LF Draes onces they return and are at a higher level.

**Comment by acidmanifesto** [comment]
So looking into you. you are actually not even supose to be able to take that quest as it is a for the alliance when they do the requirements of allied races for the lfd recruitment. we will be looking at correcting the issue here shortly. I am getting with skeezix in looking at our options in terms of restrictions.

**Comment by vikingjunior** [comment]
Hello,
Ok, then I did something wrong when starting the character. It is my first
lightforged, and indeed I took the teleporter pad you start on, and not the
"potal" one you linked , will try that when I'm back home from work.

Thanks for the fast response.


Op vr 24 sep. 2021 16:47 schreef acidmanifesto ***@***.***>:

**Comment by skeezerbean** [comment]
It's misleading, as the teleporter right where you start should only be active during another scenario/quest. I've sent some things to MDic to test to both lock that teleporter to only respond during that quest, and to make sure the teleporter outside Stormwind is visible for any Light-Forged Draenei as well as any Alliance who has the quest chain active that requires it.
I made the same mistake as you, I created a LFD (never played one) and clicked on that to be brought inside of some instance which made no sense :)

**Comment by acidmanifesto** [comment]
Fix sent in by skezzerbean and will be live next update.
