### ISSUE TITLE
[QUEST] Junk in my trunk

### ISSUE THREAD

**Issue by vikingjunior** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#914]
**Describe the bug**
the items needed in the Utgarde Pinnacle quest "Junk in my trunk" (quest=13131) ,5 Untarnished Silver Bars, 3 Shiny Baubles, 2 Golden Goblets, and a Jade Statue show up on the ground, but after the pick up animation, you get the loot screen that quickly closes again without the item being looted.

https://www.wowhead.com/quest=13131/junk-in-my-trunk

**To Reproduce**
Run UP and pick up the quest

**Expected behavior**
items being picked up, and shown in the bag.

**Comment by TheDdraig** [comment]
This issue has now been fixed, thanks for reporting.
