### ISSUE TITLE
Black Fathom Depths

### ISSUE THREAD

**Issue by Daemanis** [Project-AuroraWoW/Project-Aurora-Bug-Tracker#917]
All the void walkers of Black Fathom depths are unkillable and do not de-spawn with their summoners, leading to a situation where you have to teleport out of the dungeon and back in (to the beginning) to stop them from attacking you.  further to this the loot chest for Akumai at the end of the dungeon does not work, it glows as per boss chest loot but you are unable to loot it, clicking on it does nothing.

**Comment by TheDdraig** [comment]
Skeezix fixed this.

**Comment by skeezerbean** [comment]
Well, I fixed the void walker issue. No clue about the chest
